spring:
    application:
        name: projectsolidb
    datasource:
        url: jdbc:mysql://localhost:3306/sakila
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true

